import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header/Header";

import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className} data-theme="mytheme">
        <Header />
        <div className="py-24">
          {children}</div>
      </body>
    </html>
  );
}
